# Generated by Django 5.1.6 on 2025-02-26 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TellTheStroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PP', 'Prashant Pal'), ('AP', 'Aashsih Patel'), ('BP', 'Bittu Kumar'), ('DJ', 'Deepak Jha')], max_length=2)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
