# Generated by Django 5.1.6 on 2025-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteForjinja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellthestroy',
            name='story',
            field=models.TextField(default='Once upon a time...', max_length=1000),
        ),
    ]
