# Generated by Django 5.1.6 on 2025-02-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteForjinja', '0002_tellthestroy_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellthestroy',
            name='name',
            field=models.CharField(choices=[('Prashant Pal', 'Prashant Pal'), ('Ashish Patel', 'Ashsih Patel'), ('Bittu Kumar', 'Bittu Kumar'), ('Deepak Jha', 'Deepak Jha')], max_length=20),
        ),
    ]
