# Generated by Django 5.1.6 on 2025-02-27 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteForjinja', '0003_alter_tellthestroy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellthestroy',
            name='dateOfMemory',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tellthestroy',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tellthestroy',
            name='memoryTitle',
            field=models.CharField(default='Memory Title', max_length=100),
        ),
    ]
