# Generated by Django 5.1.6 on 2025-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteForjinja', '0004_tellthestroy_dateofmemory_tellthestroy_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellthestroy',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
